name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_BASEDIR: "${{ github.workspace }}"
    steps:
      - name: Clone Code
        id: clone
        run: |
          git clone --progress --filter=blob:none --recursive --shallow-submodules --branch dev https://github.com/re-zero001/LSPosed-Irena ./LSPosed-Irena
          cd ./LSPosed-Irena
          echo "commitHash=$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

      - name: Get Version
        id: getversion
        run: |
            Latest=$(curl -skL https://api.github.com/repos/hubbylei/Build-LSPosed-Irena/releases/latest | jq -r .tag_name | awk -F "-" '{print $2}')
            echo "commitHash=${Latest}" >> "$GITHUB_OUTPUT"

      - name: Compare Version
        id: compare
        run: |
          latestVer=${{ steps.getversion.outputs.commitHash }}
          getVer=${{ steps.clone.outputs.commitHash }}
          echo "LatestVer: ${latestVer}"
          echo "GetVer: ${getVer}"
          if [ "${latestVer}" = "${getVer}" ];then
            echo "build=false" >> "$GITHUB_OUTPUT"
          else
            echo "build=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Java
        if: steps.compare.outputs.build == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        if: steps.compare.outputs.build == 'true'
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        if: steps.compare.outputs.build == 'true'
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: 'false'
          packages: ''

      - name: Setup ccache
        if: steps.compare.outputs.build == 'true'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
            max-size: 2G
            key: ${{ runner.os }}-${{ github.sha }}
            restore-keys: ${{ runner.os }}-${{ github.sha }}

      - name: Setup Ninja
        if: steps.compare.outputs.build == 'true'
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.1

      - name: Remove Android's cmake
        if: steps.compare.outputs.build == 'true'
        shell: bash
        run: rm -rf $ANDROID_HOME/cmake

      - name: Configure Gradle properties
        if: steps.compare.outputs.build == 'true'
        working-directory: ./LSPosed-Irena
        run: |
          echo 'org.gradle.caching=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.parallel=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC' >> ~/.gradle/gradle.properties
          echo 'android.native.buildOutput=verbose' >> ~/.gradle/gradle.properties

      - name: Build with Gradle
        if: steps.compare.outputs.build == 'true'
        working-directory: ./LSPosed-Irena
        id: build
        run: |
          ./gradlew zipAll
          echo "status=success" >> "$GITHUB_OUTPUT"

      - name: Prepare artifact
        if: steps.build.outputs.status == 'success' && !cancelled()
        working-directory: ./LSPosed-Irena
        id: prepareArtifact
        run: |
          zygiskReleaseName=`ls magisk-loader/release/LSPosed-v*-Irena-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "zygiskReleaseName=$zygiskReleaseName" >> $GITHUB_OUTPUT
          zygiskDebugName=`ls magisk-loader/release/LSPosed-v*-Irena-debug.zip | awk -F '(/|.zip)' '{print $3}'` && echo "zygiskDebugName=$zygiskDebugName" >> $GITHUB_OUTPUT
          unzip magisk-loader/release/LSPosed-v*-Irena-release.zip -d LSPosed-Irena-release
          unzip magisk-loader/release/LSPosed-v*-Irena-debug.zip -d LSPosed-Irena-debug

      - name: Upload zygisk release
        if: steps.build.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskReleaseName }}
          path: "./LSPosed-Irena/LSPosed-Irena-release/*"

      - name: Upload zygisk debug
        if: steps.build.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskDebugName }}
          path: "./LSPosed-Irena/LSPosed-Irena-debug/*"

      - name: Upload mappings
        if: steps.build.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: mappings
          path: |
            ./LSPosed-Irena/magisk-loader/build/outputs/mapping
            ./LSPosed-Irena/app/build/outputs/mapping

      - name: Upload symbols
        if: steps.build.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: symbols
          path: ./LSPosed-Irena/build/symbols

      - name: Generate release tag
        if: steps.build.outputs.status == 'success' && !cancelled()
        id: tag
        run: |
          release_tag=$(echo ${{ steps.prepareArtifact.outputs.zygiskReleaseName }} | sed -r 's/LSPosed-v(.*)-Irena-release/\1/')
          echo "![](https://img.shields.io/github/downloads/${{ github.repository }}/${release_tag}/total?style=flat-square)" > release.txt
          echo "release_tag=${release_tag}" >> $GITHUB_OUTPUT

      - name: Upload Release
        if: steps.build.outputs.status == 'success' && !cancelled()
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ./LSPosed-Irena/magisk-loader/release/*.zip

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 4

      - name: Remove old Releases
        if: steps.build.outputs.status == 'success' && !cancelled()
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 48
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
